#!/usr/bin/env bash

dependencycheck() {
    numdependencies="$#"
    dependencies=("$@")
    missingdependencies=0
    for ((i = 0; i < numdependencies; i++)) ; do
        if ! command -v "${dependencies[$i]}" &> /dev/null ; then
            printf "dependency not met: %s\n" "${dependencies[$i]}"
            missingdependencies=$((missingdependencies+1))
        fi
    done
    if [ $missingdependencies -gt 0 ]; then
        exit 1
    fi
}

dependencycheck sudo chown cp chmod mkdir date awk sed rm find sort

function changeowner() {
        if command -v "doas" &> /dev/null ; then
            doas chown -R "$USER":"$USER" ./*
        else
            sudo chown -R "$USER":"$USER" ./*
        fi
}

function install_upnup() {
    if [[ ! -f /usr/local/bin/upnup ]] ; then
        printf "%s\n" 'installing upnup to /usr/local/bin ...'
        if command -v "doas" &> /dev/null ; then
            doas cp upnup /usr/local/bin/
            doas chmod 755 /usr/local/bin/upnup
        else
            sudo cp upnup /usr/local/bin/
            sudo chmod 755 /usr/local/bin/upnup
        fi
    else
        read -e -r -p "upnup already installed, would you like to reinstall?(y/n): " reinstall
        if [[ $reinstall == "y" || $reinstall == "yes" ]] ; then
            if command -v "doas" &> /dev/null ; then
                doas cp upnup /usr/local/bin/
                doas chmod 755 /usr/local/bin/upnup
            else
                sudo cp upnup /usr/local/bin/
                sudo chmod 755 /usr/local/bin/upnup
            fi
        else
            printf "%s\n" "install script exiting, no changes were made to upnup."
        fi
    fi
}

function install_annota() {
    if [[ ! -f /usr/local/bin/annota ]] ; then
        printf "%s\n" 'installing annota to /usr/local/bin ...'
        if command -v "doas" &> /dev/null ; then
            doas cp ./annotator/annota /usr/local/bin/
            doas chmod 755 /usr/local/bin/annota
        else
            sudo cp ./annotator/annota /usr/local/bin/
            sudo chmod 755 /usr/local/bin/annota
        fi
    else
        read -e -r -p "annota already installed, would you like to reinstall?(y/n): " reinstall
        if [[ $reinstall == "y" || $reinstall == "yes" ]] ; then
            if command -v "doas" &> /dev/null ; then
                doas cp ./annotator/annota /usr/local/bin/
                doas chmod 755 /usr/local/bin/annota
            else
                sudo cp ./annotator/annota /usr/local/bin/
                sudo chmod 755 /usr/local/bin/annota
            fi
        else
            printf "%s\n" "install script exiting, no changes were made to annota."
        fi
    fi
}

function createconfig() {
    if [[ ! -d "$HOME/.config/upnup/" ]] ; then
        printf "%s\n" "installing configuration files in directory ~/.config/upnup/ ..."
        mkdir -p "$HOME"/.config/upnup/
        cp -r licenses "$HOME"/.config/upnup/
        cp -r headers "$HOME"/.config/upnup/
        cp -r annotator "$HOME"/.config/upnup/
    else
        read -e -r -p "\~/.config/upnup directory already exists, would you like to overwrite configuration files?(y/n): " replaceconfig
        if [[ $replaceconfig == "y" || $replaceconfig == "yes" ]] ; then
            cp -r licenses "$HOME"/.config/upnup/
            cp -r headers "$HOME"/.config/upnup/
            cp -r annotator "$HOME"/.config/upnup/
        else
            printf "%s\n" "install script exiting, no updates to configuration have been made ..."
            exit 0
        fi
    fi
}

function installman() {
    if [[ -d "/usr/share/man/man1" ]] ; then
        if [[ ! -f /usr/share/man/man1/upnup.1.gz ]] ; then
            printf "%s\n" "installing man page in /usr/share/man/man1 ..."
            if command -v "doas" &> /dev/null ; then
                doas cp man_page/upnup.1.gz /usr/share/man/man1/
            else
                sudo cp man_page/upnup.1.gz /usr/share/man/man1/
            fi
        else
            read -e -r -p "upnup.1.gz already exists, would you like to overwrite man page?(y/n): " replaceman
            if [[ "$replaceman" == "y" || "$replaceman" == "yes" ]] ; then
                printf "%s\n" "installing man page in /usr/share/man/man1 ..."
                if command -v "doas" &> /dev/null ; then
                    doas cp man_page/upnup.1.gz /usr/share/man/man1/
                else
                    sudo cp man_page/upnup.1.gz /usr/share/man/man1/
                fi
            else
                printf "%s\n" "install script exiting, no updates man page have been made ..."
                exit 0
            fi
        fi
    else
        printf "%s\n" "/usr/share/man/man1 doesn't exist, copy upnup.1.gz to preferred man page directory manually"
        exit 0
    fi
}

changeowner
install_upnup
install_annota
createconfig
installman
