#!/usr/bin/env bash
# depends on moreutils for sponge
set -e

dependencycheck() {
    numdependencies="$#"
    dependencies=("$@")
    missingdependencies=0
    for ((i = 0; i < numdependencies; i++)) ; do
        if ! command -v "${dependencies[$i]}" &> /dev/null ; then
            printf "dependency not met: %s\n" "${dependencies[$i]}"
            missingdependencies=$((missingdependencies+1))
        fi
    done
    if [ $missingdependencies -gt 0 ]; then
        exit 1
    fi
}

dependencycheck sudo chown cp chmod mkdir date awk sed find sort

function changeowner() {
        if command -v "doas" &> /dev/null ; then
            doas chown -R "$USER":"$USER" ./*
        else
            sudo chown -R "$USER":"$USER" ./*
        fi
}

function install_lsc() {
    if [[ ! -f /usr/local/bin/lsc ]] ; then
        printf "%s\n" 'installing lsc to /usr/local/bin ...'
        if command -v "doas" &> /dev/null ; then
            doas cp lsc /usr/local/bin/
            doas chmod 755 /usr/local/bin/lsc
        else
            sudo cp lsc /usr/local/bin/
            sudo chmod 755 /usr/local/bin/lsc
        fi
    else
        read -e -r -p "lsc already installed, would you like to reinstall?(y/n): " reinstall
        if [[ $reinstall == "y" || $reinstall == "yes" ]] ; then
            if command -v "doas" &> /dev/null ; then
                doas cp lsc /usr/local/bin/
                doas chmod 755 /usr/local/bin/lsc
            else
                sudo cp lsc /usr/local/bin/
                sudo chmod 755 /usr/local/bin/lsc
            fi
        else
            printf "%s\n" "install script exiting, no changes were made to lsc."
        fi
    fi
}

function createconfig() {
    if [[ ! -d "$HOME/.config/lsc/" ]] ; then
        printf "%s\n" "installing configuration files in directory ~/.config/lsc/ ..."
        mkdir -p "$HOME"/.config/lsc/lscs
        cp -r licenses "$HOME"/.config/lsc/
        cp -r headers "$HOME"/.config/lsc/
    else
        read -e -r -p "\~/.config/lsc directory already exists, would you like to overwrite configuration files?(y/n): " replaceconfig
        if [[ $replaceconfig == "y" || $replaceconfig == "yes" ]] ; then
            cp -r licenses "$HOME"/.config/lsc/
            cp -r headers "$HOME"/.config/lsc/
        else
            printf "%s\n" "install script exiting, no updates to configuration have been made ..."
            exit 0
        fi
    fi
}

# function installman() {
    # if [[ -d "/usr/share/man/man1" ]] ; then
        # printf "%s\n" "installing man page in /usr/share/man/man1 ..."
        # if command -v "doas" &> /dev/null ; then
            # doas cp man_page/lsc.1.gz /usr/share/man/man1/
        # else
            # sudo cp man_page/lsc.1.gz /usr/share/man/man1/
        # fi
    # else
        # printf "%s\n" "/usr/share/man/man1 doesn't exist, copy lsc.1.gz to preferred man page directory manually"
        # exit 0
    # fi
# }

changeowner
install_lsc
createconfig
# installman
