#!/usr/bin/env bash
set -e

dependencycheck() {
    numdependencies="$#"
    dependencies=("$@")
    missingdependencies=0
    for ((i = 0; i < numdependencies; i++)) ; do
        if ! command -v "${dependencies[$i]}" &> /dev/null ; then
            printf "dependency not met: %s\n" "${dependencies[$i]}"
            missingdependencies=$((missingdependencies+1))
        fi
    done
    if [ $missingdependencies -gt 0 ]; then
        exit 1
    fi
}

dependencycheck sudo chown cp chmod mkdir

function removelsc() {
    if [[ -f /usr/local/bin/lsc ]] ; then
        if command -v "doas" &> /dev/null ; then
            doas rm /usr/local/bin/lsc
            printf "%s\n" "removing /usr/local/bin/lsc ..."
        else
            sudo rm /usr/local/bin/lsc
            printf "%s\n" "removing /usr/local/bin/lsc ..."
        fi
    fi
}

function removeconfig() {
    if [[ -d "$HOME/.config/lsc/" ]] ; then
        printf "%s\n" "removing ~/.config/lsc ..."
        if command -v "doas" &> /dev/null ; then
            doas rm -r "$HOME"/.config/lsc
        else
            sudo rm -r "$HOME"/.config/lsc
        fi
    fi
}

# function removeman() {
    # if [[ -f "/usr/share/man/man1/lsc.1.gz" ]] ; then
        # printf "%s\n" "removing man page /usr/share/man/man1/lsc.1.gz ..."
        # if command -v "doas" &> /dev/null ; then
            # doas rm /usr/share/man/man1/lsc.1.gz
        # else
            # sudo rm /usr/share/man/man1/lsc.1.gz
        # fi
    # fi
# }

removelsc
removeconfig
# removeman
