#!/usr/bin/env bash
set -e

dependencycheck() {
    numdependencies="$#"
    dependencies=("$@")
    missingdependencies=0
    for ((i = 0; i < numdependencies; i++)) ; do
        if ! command -v "${dependencies[$i]}" &> /dev/null ; then
            printf "dependency not met: %s\n" "${dependencies[$i]}"
            missingdependencies=$((missingdependencies+1))
        fi
    done
    if [ $missingdependencies -gt 0 ]; then
        exit 1
    fi
}

dependencycheck sudo chown cp chmod mkdir

function removelicense() {
    if [[ -f /usr/local/bin/license ]] ; then
        if command -v "doas" &> /dev/null ; then
            doas rm /usr/local/bin/license
            echo "removing /usr/local/bin/license ..."
        else
            sudo rm /usr/local/bin/license
            echo "removing /usr/local/bin/license ..."
        fi
    fi
}

function removeconfig() {
    if [[ -d "$HOME/.config/license/" ]] ; then
        echo "removing ~/.config/license ..."
        if command -v "doas" &> /dev/null ; then
            doas rm -r "$HOME"/.config/license
        else
            sudo rm -r "$HOME"/.config/license
        fi
    fi
}

# function removeman() {
    # if [[ -f "/usr/share/man/man1/license.1.gz" ]] ; then
        # echo "removing man page /usr/share/man/man1/license.1.gz ..."
        # if command -v "doas" &> /dev/null ; then
            # doas rm /usr/share/man/man1/license.1.gz
        # else
            # sudo rm /usr/share/man/man1/license.1.gz
        # fi
    # fi
# }

removelicense
removeconfig
# removeman
