.TH UPNUP 1L 2022-09-29 Info-UPNUP

.SH NAME
upnup \- generate licenses from the command line

.SH SYNOPSIS
.B upnup
[\fB\-V/--version\fR]
[\fB\-h/--help\fR]
[\fB\-u/--user\fR]
[\fB\-y/--year\fR]
[\fB\-f/--file\fR]

.SH DESCRIPTION
upnup allows you to automatically generate a LICENSE file for the current working directory that you are in or a license header for a file where applicable.

.SH DEFAULTS
upnup can be invoked using the command with the p flag followed by the name of
the desired license. It will look for the $USER variable and input that under
any [fullname] fields in the license. upnup also uses the date command line tool
to determine the current year, which it then inserts into any [year] fields.
When using the -f option, [projectname] will default to current directory. It is
advised to invoke upnup with the -f flag at project root directory.

.SH OPTIONS
.TP
.BR \-V, --version
output version information and exit
.TP
.BR \-h, \--help
display help message and exit (you will also receive this message if you pass no arguments)
.TP
.BR \-u, \--user \ [username]
input the username or organization of who holds the license
.TP
.BR \-y, \--year \ [year]
input the year the license is in effect
.TP
.BR \-f, \--file \ <file>
prepend a license header to a file (call from project root directory)
.TP
.BR \ l, list
list all available licenses
.TP
.BR \ p, put \ <filename\ or\ license>
put a license in current directory (when called with -f flag, specify the file to
add headers to. otherwise, enter license name).

.SH FILES
.TP
.I /usr/local/bin/upnup /usr/local/bin/annota
the shell scripts are located in /usr/local/bin.
.TP
.I ~/.config/upnup
all configuration files can be found here

.SH SYNOPSES OF LICENSES (see choosealicense.com)
.TP
.SH GNU AFFERO GENERAL PUBLIC LICENSE v3.0 (agpl-3.0)
Permissions of this strongest copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, patent use, private use
.TP
.BR
.I\ Conditions
disclose source, license and copyright notice, network use is distribution, same license, state changes
.TP
.BR
.I\ Limitations
liability, warranty
.TP
.SH APACHE LICENSE 2.0 (apache-2.0)
A permissive license whose main conditions require preservation of copyright and license notices. Contributors provide an express grant of patent rights. Licensed works, modifications, and larger works may be distributed under different terms and without source code.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, patent use, private use
.TP
.BR
.I\ Conditions
license and copyright notice, state changes
.TP
.BR
.I\ Limitations
liability, trademark use, warranty
.TP
.SH BSD 2-CLAUSE "SIMPLIFIED" LICENSE (bsd-2-clause)
A permissive license that comes in two variants, the BSD 2-Clause and BSD 3-Clause. Both have very minute differences to the MIT license.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, private use
.TP
.BR
.I\ Conditions
license and copyright notice
.TP
.BR
.I\ Limitations
liability, warranty
.TP
.SH BSD 3-CLAUSE CLEAR LICENSE (bsd-3-clause)
A variant of the BSD 3-Clause License that explicitly does not grant any patent rights.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, private use
.TP
.BR
.I\ Conditions
license and copyright notice
.TP
.BR
.I\ Limitations
liability, patent use, warranty
.TP
.SH BOOST SOFTWARE LICENSE 1.0 (bsl-1.0)
A simple permissive license only requiring preservation of copyright and license notices for source (and not binary) distribution. Licensed works, modifications, and larger works may be distributed under different terms and without source code.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, private use
.TP
.BR
.I\ Conditions
license and copyright notice for source
.TP
.BR
.I\ Limitations
liability, warranty
.TP
.SH CREATIVE COMMONS ZERO v1.0 UNIVERSAL (cc0-1.0)
The Creative Commons CC0 Public Domain Dedication waives copyright interest in a work you've created and dedicates it to the world-wide public domain. Use CC0 to opt out of copyright entirely and ensure your work has the widest reach. As with the Unlicense and typical software licenses, CC0 disclaims warranties. CC0 is very similar to the Unlicense.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, private use
.TP
.BR
.I\ Conditions
none
.TP
.BR
.I\ Limitations
liability, patent use, trademark use, warranty
.TP
.SH CREATIVE COMMONS ATTRIBUTION 4.0 INTERNATIONAL (cc0-4.0)
Permits almost any use subject to providing credit and license notice. Frequently used for media assets and educational materials. The most common license for Open Access scientific publications. Not recommended for software.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, private use
.TP
.BR
.I\ Conditions
license and copyright notice, state changes
.TP
.BR
.I\ Limitations
liability, patent use, trademark use, warranty
.TP
.SH ECLIPSE PUBLIC LICENSE 2.0 (epl-2.0)
This commercially-friendly copyleft license provides the ability to commercially license binaries; a modern royalty-free patent license grant; and the ability for linked works to use other licenses, including commercial ones.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, patent use, private use
.TP
.BR
.I\ Conditions
disclose source, license and copyright notice, same license
.TP
.BR
.I\ Limitations
liability, warranty
.TP
.SH GNU GENERAL PUBLIC LICENSE v2.0 (gpl-2.0)
The GNU GPL is the most widely used free software license and has a strong copyleft requirement. When distributing derived works, the source code of the work must be made available under the same license. There are multiple variants of the GNU GPL, each with different requirements.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, private use
.TP
.BR
.I\ Conditions
disclose source, license and copyright notice, same license, state changes
.TP
.BR
.I\ Limitations
liability, warranty
.TP
.SH GNU GENERAL PUBLIC LICENSE v3.0 (gpl-3.0)
Permissions of this strong copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, patent use, private use
.TP
.BR
.I\ Conditions
disclose source, license and copyright notice, same license, state changes
.TP
.BR
.I\ Limitations
liability, warranty
.TP
.SH GNU LESSER GENERAL PUBLIC LICENSE v2.1 (lgpl-2.1)
Primarily used for software libraries, the GNU LGPL requires that derived works be licensed under the same license, but works that only link to it do not fall under this restriction. There are two commonly used versions of the GNU LGPL.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, private use
.TP
.BR
.I\ Conditions
disclose source, license and copyright notice, same license (library), state changes
.TP
.BR
.I\ Limitations
liability, warranty
.TP
.SH MIT LICENSE (mit)
A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, private use
.TP
.BR
.I\ Conditions
license and copyright notice
.TP
.BR
.I\ Limitations
liability, warranty
.TP
.SH MOZILLA PUBLIC LICENSE 2.0 (mpl-2.0)
Permissions of this weak copyleft license are conditioned on making available source code of licensed files and modifications of those files under the same license (or in certain cases, one of the GNU licenses). Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. However, a larger work using the licensed work may be distributed under different terms and without source code for files added in the larger work.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, patent use, private use
.TP
.BR
.I\ Conditions
disclose source, license and copyright notice, same license (file)
.TP
.BR
.I\ Limitations
liability, trademark use, warranty
.TP
.SH THE UNLICENSE (unlicense)
A license with no conditions whatsoever which dedicates works to the public domain. Unlicensed works, modifications, and larger works may be distributed under different terms and without source code.
.TP
.BR
.I\ Permissions
commercial use, distribution, modification, private use
.TP
.BR
.I\ Conditions
none
.TP
.BR
.I\ Limitations
liability, warranty

.SH DISCLAIMER
All content in this document is intended as general information only, and should
not be construed as legal advice.

.SH AUTHOR
z3rOR0ne <z3rOR0ne@protonmail.com>

.SH SEE ALSO
\fBlegit\fR
\fBcommentator\fR
